// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_cache.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_http_5fcache_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_http_5fcache_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_http_5fcache_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_http_5fcache_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_http_5fcache_2eproto;
namespace hpserver {
namespace cache {
class HeaderEntry;
struct HeaderEntryDefaultTypeInternal;
extern HeaderEntryDefaultTypeInternal _HeaderEntry_default_instance_;
class HttpCacheEntry;
struct HttpCacheEntryDefaultTypeInternal;
extern HttpCacheEntryDefaultTypeInternal _HttpCacheEntry_default_instance_;
}  // namespace cache
}  // namespace hpserver
PROTOBUF_NAMESPACE_OPEN
template<> ::hpserver::cache::HeaderEntry* Arena::CreateMaybeMessage<::hpserver::cache::HeaderEntry>(Arena*);
template<> ::hpserver::cache::HttpCacheEntry* Arena::CreateMaybeMessage<::hpserver::cache::HttpCacheEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hpserver {
namespace cache {

// ===================================================================

class HeaderEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hpserver.cache.HeaderEntry) */ {
 public:
  inline HeaderEntry() : HeaderEntry(nullptr) {}
  ~HeaderEntry() override;
  explicit PROTOBUF_CONSTEXPR HeaderEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeaderEntry(const HeaderEntry& from);
  HeaderEntry(HeaderEntry&& from) noexcept
    : HeaderEntry() {
    *this = ::std::move(from);
  }

  inline HeaderEntry& operator=(const HeaderEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeaderEntry& operator=(HeaderEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeaderEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeaderEntry* internal_default_instance() {
    return reinterpret_cast<const HeaderEntry*>(
               &_HeaderEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HeaderEntry& a, HeaderEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(HeaderEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeaderEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeaderEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeaderEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeaderEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeaderEntry& from) {
    HeaderEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeaderEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hpserver.cache.HeaderEntry";
  }
  protected:
  explicit HeaderEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // string value = 2;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:hpserver.cache.HeaderEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_http_5fcache_2eproto;
};
// -------------------------------------------------------------------

class HttpCacheEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hpserver.cache.HttpCacheEntry) */ {
 public:
  inline HttpCacheEntry() : HttpCacheEntry(nullptr) {}
  ~HttpCacheEntry() override;
  explicit PROTOBUF_CONSTEXPR HttpCacheEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HttpCacheEntry(const HttpCacheEntry& from);
  HttpCacheEntry(HttpCacheEntry&& from) noexcept
    : HttpCacheEntry() {
    *this = ::std::move(from);
  }

  inline HttpCacheEntry& operator=(const HttpCacheEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline HttpCacheEntry& operator=(HttpCacheEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HttpCacheEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const HttpCacheEntry* internal_default_instance() {
    return reinterpret_cast<const HttpCacheEntry*>(
               &_HttpCacheEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HttpCacheEntry& a, HttpCacheEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(HttpCacheEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HttpCacheEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HttpCacheEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HttpCacheEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HttpCacheEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HttpCacheEntry& from) {
    HttpCacheEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HttpCacheEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hpserver.cache.HttpCacheEntry";
  }
  protected:
  explicit HttpCacheEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadersFieldNumber = 7,
    kVaryHeadersFieldNumber = 9,
    kReasonPhraseFieldNumber = 2,
    kLastModifiedFieldNumber = 3,
    kEtagFieldNumber = 4,
    kBodyFieldNumber = 8,
    kStoredAtUnixSecFieldNumber = 5,
    kTtlSecFieldNumber = 6,
    kStatusCodeFieldNumber = 1,
  };
  // repeated .hpserver.cache.HeaderEntry headers = 7;
  int headers_size() const;
  private:
  int _internal_headers_size() const;
  public:
  void clear_headers();
  ::hpserver::cache::HeaderEntry* mutable_headers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hpserver::cache::HeaderEntry >*
      mutable_headers();
  private:
  const ::hpserver::cache::HeaderEntry& _internal_headers(int index) const;
  ::hpserver::cache::HeaderEntry* _internal_add_headers();
  public:
  const ::hpserver::cache::HeaderEntry& headers(int index) const;
  ::hpserver::cache::HeaderEntry* add_headers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hpserver::cache::HeaderEntry >&
      headers() const;

  // repeated string vary_headers = 9;
  int vary_headers_size() const;
  private:
  int _internal_vary_headers_size() const;
  public:
  void clear_vary_headers();
  const std::string& vary_headers(int index) const;
  std::string* mutable_vary_headers(int index);
  void set_vary_headers(int index, const std::string& value);
  void set_vary_headers(int index, std::string&& value);
  void set_vary_headers(int index, const char* value);
  void set_vary_headers(int index, const char* value, size_t size);
  std::string* add_vary_headers();
  void add_vary_headers(const std::string& value);
  void add_vary_headers(std::string&& value);
  void add_vary_headers(const char* value);
  void add_vary_headers(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& vary_headers() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_vary_headers();
  private:
  const std::string& _internal_vary_headers(int index) const;
  std::string* _internal_add_vary_headers();
  public:

  // string reason_phrase = 2;
  void clear_reason_phrase();
  const std::string& reason_phrase() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason_phrase(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason_phrase();
  PROTOBUF_NODISCARD std::string* release_reason_phrase();
  void set_allocated_reason_phrase(std::string* reason_phrase);
  private:
  const std::string& _internal_reason_phrase() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason_phrase(const std::string& value);
  std::string* _internal_mutable_reason_phrase();
  public:

  // string last_modified = 3;
  void clear_last_modified();
  const std::string& last_modified() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_last_modified(ArgT0&& arg0, ArgT... args);
  std::string* mutable_last_modified();
  PROTOBUF_NODISCARD std::string* release_last_modified();
  void set_allocated_last_modified(std::string* last_modified);
  private:
  const std::string& _internal_last_modified() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_last_modified(const std::string& value);
  std::string* _internal_mutable_last_modified();
  public:

  // string etag = 4;
  void clear_etag();
  const std::string& etag() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_etag(ArgT0&& arg0, ArgT... args);
  std::string* mutable_etag();
  PROTOBUF_NODISCARD std::string* release_etag();
  void set_allocated_etag(std::string* etag);
  private:
  const std::string& _internal_etag() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_etag(const std::string& value);
  std::string* _internal_mutable_etag();
  public:

  // bytes body = 8;
  void clear_body();
  const std::string& body() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_body(ArgT0&& arg0, ArgT... args);
  std::string* mutable_body();
  PROTOBUF_NODISCARD std::string* release_body();
  void set_allocated_body(std::string* body);
  private:
  const std::string& _internal_body() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_body(const std::string& value);
  std::string* _internal_mutable_body();
  public:

  // int64 stored_at_unix_sec = 5;
  void clear_stored_at_unix_sec();
  int64_t stored_at_unix_sec() const;
  void set_stored_at_unix_sec(int64_t value);
  private:
  int64_t _internal_stored_at_unix_sec() const;
  void _internal_set_stored_at_unix_sec(int64_t value);
  public:

  // int64 ttl_sec = 6;
  void clear_ttl_sec();
  int64_t ttl_sec() const;
  void set_ttl_sec(int64_t value);
  private:
  int64_t _internal_ttl_sec() const;
  void _internal_set_ttl_sec(int64_t value);
  public:

  // uint32 status_code = 1;
  void clear_status_code();
  uint32_t status_code() const;
  void set_status_code(uint32_t value);
  private:
  uint32_t _internal_status_code() const;
  void _internal_set_status_code(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:hpserver.cache.HttpCacheEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hpserver::cache::HeaderEntry > headers_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> vary_headers_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_phrase_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr last_modified_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr etag_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr body_;
    int64_t stored_at_unix_sec_;
    int64_t ttl_sec_;
    uint32_t status_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_http_5fcache_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HeaderEntry

// string key = 1;
inline void HeaderEntry::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& HeaderEntry::key() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HeaderEntry.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HeaderEntry::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hpserver.cache.HeaderEntry.key)
}
inline std::string* HeaderEntry::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HeaderEntry.key)
  return _s;
}
inline const std::string& HeaderEntry::_internal_key() const {
  return _impl_.key_.Get();
}
inline void HeaderEntry::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* HeaderEntry::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* HeaderEntry::release_key() {
  // @@protoc_insertion_point(field_release:hpserver.cache.HeaderEntry.key)
  return _impl_.key_.Release();
}
inline void HeaderEntry::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hpserver.cache.HeaderEntry.key)
}

// string value = 2;
inline void HeaderEntry::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& HeaderEntry::value() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HeaderEntry.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HeaderEntry::set_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hpserver.cache.HeaderEntry.value)
}
inline std::string* HeaderEntry::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HeaderEntry.value)
  return _s;
}
inline const std::string& HeaderEntry::_internal_value() const {
  return _impl_.value_.Get();
}
inline void HeaderEntry::_internal_set_value(const std::string& value) {
  
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* HeaderEntry::_internal_mutable_value() {
  
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* HeaderEntry::release_value() {
  // @@protoc_insertion_point(field_release:hpserver.cache.HeaderEntry.value)
  return _impl_.value_.Release();
}
inline void HeaderEntry::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hpserver.cache.HeaderEntry.value)
}

// -------------------------------------------------------------------

// HttpCacheEntry

// uint32 status_code = 1;
inline void HttpCacheEntry::clear_status_code() {
  _impl_.status_code_ = 0u;
}
inline uint32_t HttpCacheEntry::_internal_status_code() const {
  return _impl_.status_code_;
}
inline uint32_t HttpCacheEntry::status_code() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.status_code)
  return _internal_status_code();
}
inline void HttpCacheEntry::_internal_set_status_code(uint32_t value) {
  
  _impl_.status_code_ = value;
}
inline void HttpCacheEntry::set_status_code(uint32_t value) {
  _internal_set_status_code(value);
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.status_code)
}

// string reason_phrase = 2;
inline void HttpCacheEntry::clear_reason_phrase() {
  _impl_.reason_phrase_.ClearToEmpty();
}
inline const std::string& HttpCacheEntry::reason_phrase() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.reason_phrase)
  return _internal_reason_phrase();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HttpCacheEntry::set_reason_phrase(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_phrase_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.reason_phrase)
}
inline std::string* HttpCacheEntry::mutable_reason_phrase() {
  std::string* _s = _internal_mutable_reason_phrase();
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HttpCacheEntry.reason_phrase)
  return _s;
}
inline const std::string& HttpCacheEntry::_internal_reason_phrase() const {
  return _impl_.reason_phrase_.Get();
}
inline void HttpCacheEntry::_internal_set_reason_phrase(const std::string& value) {
  
  _impl_.reason_phrase_.Set(value, GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::_internal_mutable_reason_phrase() {
  
  return _impl_.reason_phrase_.Mutable(GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::release_reason_phrase() {
  // @@protoc_insertion_point(field_release:hpserver.cache.HttpCacheEntry.reason_phrase)
  return _impl_.reason_phrase_.Release();
}
inline void HttpCacheEntry::set_allocated_reason_phrase(std::string* reason_phrase) {
  if (reason_phrase != nullptr) {
    
  } else {
    
  }
  _impl_.reason_phrase_.SetAllocated(reason_phrase, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_phrase_.IsDefault()) {
    _impl_.reason_phrase_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hpserver.cache.HttpCacheEntry.reason_phrase)
}

// string last_modified = 3;
inline void HttpCacheEntry::clear_last_modified() {
  _impl_.last_modified_.ClearToEmpty();
}
inline const std::string& HttpCacheEntry::last_modified() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.last_modified)
  return _internal_last_modified();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HttpCacheEntry::set_last_modified(ArgT0&& arg0, ArgT... args) {
 
 _impl_.last_modified_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.last_modified)
}
inline std::string* HttpCacheEntry::mutable_last_modified() {
  std::string* _s = _internal_mutable_last_modified();
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HttpCacheEntry.last_modified)
  return _s;
}
inline const std::string& HttpCacheEntry::_internal_last_modified() const {
  return _impl_.last_modified_.Get();
}
inline void HttpCacheEntry::_internal_set_last_modified(const std::string& value) {
  
  _impl_.last_modified_.Set(value, GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::_internal_mutable_last_modified() {
  
  return _impl_.last_modified_.Mutable(GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::release_last_modified() {
  // @@protoc_insertion_point(field_release:hpserver.cache.HttpCacheEntry.last_modified)
  return _impl_.last_modified_.Release();
}
inline void HttpCacheEntry::set_allocated_last_modified(std::string* last_modified) {
  if (last_modified != nullptr) {
    
  } else {
    
  }
  _impl_.last_modified_.SetAllocated(last_modified, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.last_modified_.IsDefault()) {
    _impl_.last_modified_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hpserver.cache.HttpCacheEntry.last_modified)
}

// string etag = 4;
inline void HttpCacheEntry::clear_etag() {
  _impl_.etag_.ClearToEmpty();
}
inline const std::string& HttpCacheEntry::etag() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.etag)
  return _internal_etag();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HttpCacheEntry::set_etag(ArgT0&& arg0, ArgT... args) {
 
 _impl_.etag_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.etag)
}
inline std::string* HttpCacheEntry::mutable_etag() {
  std::string* _s = _internal_mutable_etag();
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HttpCacheEntry.etag)
  return _s;
}
inline const std::string& HttpCacheEntry::_internal_etag() const {
  return _impl_.etag_.Get();
}
inline void HttpCacheEntry::_internal_set_etag(const std::string& value) {
  
  _impl_.etag_.Set(value, GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::_internal_mutable_etag() {
  
  return _impl_.etag_.Mutable(GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::release_etag() {
  // @@protoc_insertion_point(field_release:hpserver.cache.HttpCacheEntry.etag)
  return _impl_.etag_.Release();
}
inline void HttpCacheEntry::set_allocated_etag(std::string* etag) {
  if (etag != nullptr) {
    
  } else {
    
  }
  _impl_.etag_.SetAllocated(etag, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.etag_.IsDefault()) {
    _impl_.etag_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hpserver.cache.HttpCacheEntry.etag)
}

// int64 stored_at_unix_sec = 5;
inline void HttpCacheEntry::clear_stored_at_unix_sec() {
  _impl_.stored_at_unix_sec_ = int64_t{0};
}
inline int64_t HttpCacheEntry::_internal_stored_at_unix_sec() const {
  return _impl_.stored_at_unix_sec_;
}
inline int64_t HttpCacheEntry::stored_at_unix_sec() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.stored_at_unix_sec)
  return _internal_stored_at_unix_sec();
}
inline void HttpCacheEntry::_internal_set_stored_at_unix_sec(int64_t value) {
  
  _impl_.stored_at_unix_sec_ = value;
}
inline void HttpCacheEntry::set_stored_at_unix_sec(int64_t value) {
  _internal_set_stored_at_unix_sec(value);
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.stored_at_unix_sec)
}

// int64 ttl_sec = 6;
inline void HttpCacheEntry::clear_ttl_sec() {
  _impl_.ttl_sec_ = int64_t{0};
}
inline int64_t HttpCacheEntry::_internal_ttl_sec() const {
  return _impl_.ttl_sec_;
}
inline int64_t HttpCacheEntry::ttl_sec() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.ttl_sec)
  return _internal_ttl_sec();
}
inline void HttpCacheEntry::_internal_set_ttl_sec(int64_t value) {
  
  _impl_.ttl_sec_ = value;
}
inline void HttpCacheEntry::set_ttl_sec(int64_t value) {
  _internal_set_ttl_sec(value);
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.ttl_sec)
}

// repeated .hpserver.cache.HeaderEntry headers = 7;
inline int HttpCacheEntry::_internal_headers_size() const {
  return _impl_.headers_.size();
}
inline int HttpCacheEntry::headers_size() const {
  return _internal_headers_size();
}
inline void HttpCacheEntry::clear_headers() {
  _impl_.headers_.Clear();
}
inline ::hpserver::cache::HeaderEntry* HttpCacheEntry::mutable_headers(int index) {
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HttpCacheEntry.headers)
  return _impl_.headers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hpserver::cache::HeaderEntry >*
HttpCacheEntry::mutable_headers() {
  // @@protoc_insertion_point(field_mutable_list:hpserver.cache.HttpCacheEntry.headers)
  return &_impl_.headers_;
}
inline const ::hpserver::cache::HeaderEntry& HttpCacheEntry::_internal_headers(int index) const {
  return _impl_.headers_.Get(index);
}
inline const ::hpserver::cache::HeaderEntry& HttpCacheEntry::headers(int index) const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.headers)
  return _internal_headers(index);
}
inline ::hpserver::cache::HeaderEntry* HttpCacheEntry::_internal_add_headers() {
  return _impl_.headers_.Add();
}
inline ::hpserver::cache::HeaderEntry* HttpCacheEntry::add_headers() {
  ::hpserver::cache::HeaderEntry* _add = _internal_add_headers();
  // @@protoc_insertion_point(field_add:hpserver.cache.HttpCacheEntry.headers)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hpserver::cache::HeaderEntry >&
HttpCacheEntry::headers() const {
  // @@protoc_insertion_point(field_list:hpserver.cache.HttpCacheEntry.headers)
  return _impl_.headers_;
}

// bytes body = 8;
inline void HttpCacheEntry::clear_body() {
  _impl_.body_.ClearToEmpty();
}
inline const std::string& HttpCacheEntry::body() const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.body)
  return _internal_body();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HttpCacheEntry::set_body(ArgT0&& arg0, ArgT... args) {
 
 _impl_.body_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.body)
}
inline std::string* HttpCacheEntry::mutable_body() {
  std::string* _s = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HttpCacheEntry.body)
  return _s;
}
inline const std::string& HttpCacheEntry::_internal_body() const {
  return _impl_.body_.Get();
}
inline void HttpCacheEntry::_internal_set_body(const std::string& value) {
  
  _impl_.body_.Set(value, GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::_internal_mutable_body() {
  
  return _impl_.body_.Mutable(GetArenaForAllocation());
}
inline std::string* HttpCacheEntry::release_body() {
  // @@protoc_insertion_point(field_release:hpserver.cache.HttpCacheEntry.body)
  return _impl_.body_.Release();
}
inline void HttpCacheEntry::set_allocated_body(std::string* body) {
  if (body != nullptr) {
    
  } else {
    
  }
  _impl_.body_.SetAllocated(body, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.body_.IsDefault()) {
    _impl_.body_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hpserver.cache.HttpCacheEntry.body)
}

// repeated string vary_headers = 9;
inline int HttpCacheEntry::_internal_vary_headers_size() const {
  return _impl_.vary_headers_.size();
}
inline int HttpCacheEntry::vary_headers_size() const {
  return _internal_vary_headers_size();
}
inline void HttpCacheEntry::clear_vary_headers() {
  _impl_.vary_headers_.Clear();
}
inline std::string* HttpCacheEntry::add_vary_headers() {
  std::string* _s = _internal_add_vary_headers();
  // @@protoc_insertion_point(field_add_mutable:hpserver.cache.HttpCacheEntry.vary_headers)
  return _s;
}
inline const std::string& HttpCacheEntry::_internal_vary_headers(int index) const {
  return _impl_.vary_headers_.Get(index);
}
inline const std::string& HttpCacheEntry::vary_headers(int index) const {
  // @@protoc_insertion_point(field_get:hpserver.cache.HttpCacheEntry.vary_headers)
  return _internal_vary_headers(index);
}
inline std::string* HttpCacheEntry::mutable_vary_headers(int index) {
  // @@protoc_insertion_point(field_mutable:hpserver.cache.HttpCacheEntry.vary_headers)
  return _impl_.vary_headers_.Mutable(index);
}
inline void HttpCacheEntry::set_vary_headers(int index, const std::string& value) {
  _impl_.vary_headers_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline void HttpCacheEntry::set_vary_headers(int index, std::string&& value) {
  _impl_.vary_headers_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline void HttpCacheEntry::set_vary_headers(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.vary_headers_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline void HttpCacheEntry::set_vary_headers(int index, const char* value, size_t size) {
  _impl_.vary_headers_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline std::string* HttpCacheEntry::_internal_add_vary_headers() {
  return _impl_.vary_headers_.Add();
}
inline void HttpCacheEntry::add_vary_headers(const std::string& value) {
  _impl_.vary_headers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline void HttpCacheEntry::add_vary_headers(std::string&& value) {
  _impl_.vary_headers_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline void HttpCacheEntry::add_vary_headers(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.vary_headers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline void HttpCacheEntry::add_vary_headers(const char* value, size_t size) {
  _impl_.vary_headers_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:hpserver.cache.HttpCacheEntry.vary_headers)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
HttpCacheEntry::vary_headers() const {
  // @@protoc_insertion_point(field_list:hpserver.cache.HttpCacheEntry.vary_headers)
  return _impl_.vary_headers_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
HttpCacheEntry::mutable_vary_headers() {
  // @@protoc_insertion_point(field_mutable_list:hpserver.cache.HttpCacheEntry.vary_headers)
  return &_impl_.vary_headers_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace cache
}  // namespace hpserver

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_http_5fcache_2eproto
