// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_cache.proto

#include "http_cache.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hpserver {
namespace cache {
PROTOBUF_CONSTEXPR HeaderEntry::HeaderEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HeaderEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeaderEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeaderEntryDefaultTypeInternal() {}
  union {
    HeaderEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeaderEntryDefaultTypeInternal _HeaderEntry_default_instance_;
PROTOBUF_CONSTEXPR HttpCacheEntry::HttpCacheEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.headers_)*/{}
  , /*decltype(_impl_.vary_headers_)*/{}
  , /*decltype(_impl_.reason_phrase_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.last_modified_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.etag_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.body_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stored_at_unix_sec_)*/int64_t{0}
  , /*decltype(_impl_.ttl_sec_)*/int64_t{0}
  , /*decltype(_impl_.status_code_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HttpCacheEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HttpCacheEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HttpCacheEntryDefaultTypeInternal() {}
  union {
    HttpCacheEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HttpCacheEntryDefaultTypeInternal _HttpCacheEntry_default_instance_;
}  // namespace cache
}  // namespace hpserver
static ::_pb::Metadata file_level_metadata_http_5fcache_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_http_5fcache_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_http_5fcache_2eproto = nullptr;

const uint32_t TableStruct_http_5fcache_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HeaderEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HeaderEntry, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HeaderEntry, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.status_code_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.reason_phrase_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.last_modified_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.etag_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.stored_at_unix_sec_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.ttl_sec_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.headers_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.body_),
  PROTOBUF_FIELD_OFFSET(::hpserver::cache::HttpCacheEntry, _impl_.vary_headers_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::hpserver::cache::HeaderEntry)},
  { 8, -1, -1, sizeof(::hpserver::cache::HttpCacheEntry)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hpserver::cache::_HeaderEntry_default_instance_._instance,
  &::hpserver::cache::_HttpCacheEntry_default_instance_._instance,
};

const char descriptor_table_protodef_http_5fcache_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020http_cache.proto\022\016hpserver.cache\")\n\013He"
  "aderEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\340\001"
  "\n\016HttpCacheEntry\022\023\n\013status_code\030\001 \001(\r\022\025\n"
  "\rreason_phrase\030\002 \001(\t\022\025\n\rlast_modified\030\003 "
  "\001(\t\022\014\n\004etag\030\004 \001(\t\022\032\n\022stored_at_unix_sec\030"
  "\005 \001(\003\022\017\n\007ttl_sec\030\006 \001(\003\022,\n\007headers\030\007 \003(\0132"
  "\033.hpserver.cache.HeaderEntry\022\014\n\004body\030\010 \001"
  "(\014\022\024\n\014vary_headers\030\t \003(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_http_5fcache_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_http_5fcache_2eproto = {
    false, false, 312, descriptor_table_protodef_http_5fcache_2eproto,
    "http_cache.proto",
    &descriptor_table_http_5fcache_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_http_5fcache_2eproto::offsets,
    file_level_metadata_http_5fcache_2eproto, file_level_enum_descriptors_http_5fcache_2eproto,
    file_level_service_descriptors_http_5fcache_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_http_5fcache_2eproto_getter() {
  return &descriptor_table_http_5fcache_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_http_5fcache_2eproto(&descriptor_table_http_5fcache_2eproto);
namespace hpserver {
namespace cache {

// ===================================================================

class HeaderEntry::_Internal {
 public:
};

HeaderEntry::HeaderEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hpserver.cache.HeaderEntry)
}
HeaderEntry::HeaderEntry(const HeaderEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HeaderEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:hpserver.cache.HeaderEntry)
}

inline void HeaderEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

HeaderEntry::~HeaderEntry() {
  // @@protoc_insertion_point(destructor:hpserver.cache.HeaderEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HeaderEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_.Destroy();
  _impl_.value_.Destroy();
}

void HeaderEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HeaderEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:hpserver.cache.HeaderEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeaderEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hpserver.cache.HeaderEntry.key"));
        } else
          goto handle_unusual;
        continue;
      // string value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hpserver.cache.HeaderEntry.value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HeaderEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hpserver.cache.HeaderEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hpserver.cache.HeaderEntry.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hpserver.cache.HeaderEntry.value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hpserver.cache.HeaderEntry)
  return target;
}

size_t HeaderEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hpserver.cache.HeaderEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeaderEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HeaderEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeaderEntry::GetClassData() const { return &_class_data_; }


void HeaderEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HeaderEntry*>(&to_msg);
  auto& from = static_cast<const HeaderEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hpserver.cache.HeaderEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HeaderEntry::CopyFrom(const HeaderEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hpserver.cache.HeaderEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeaderEntry::IsInitialized() const {
  return true;
}

void HeaderEntry::InternalSwap(HeaderEntry* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata HeaderEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_http_5fcache_2eproto_getter, &descriptor_table_http_5fcache_2eproto_once,
      file_level_metadata_http_5fcache_2eproto[0]);
}

// ===================================================================

class HttpCacheEntry::_Internal {
 public:
};

HttpCacheEntry::HttpCacheEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hpserver.cache.HttpCacheEntry)
}
HttpCacheEntry::HttpCacheEntry(const HttpCacheEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HttpCacheEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.headers_){from._impl_.headers_}
    , decltype(_impl_.vary_headers_){from._impl_.vary_headers_}
    , decltype(_impl_.reason_phrase_){}
    , decltype(_impl_.last_modified_){}
    , decltype(_impl_.etag_){}
    , decltype(_impl_.body_){}
    , decltype(_impl_.stored_at_unix_sec_){}
    , decltype(_impl_.ttl_sec_){}
    , decltype(_impl_.status_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.reason_phrase_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_phrase_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reason_phrase().empty()) {
    _this->_impl_.reason_phrase_.Set(from._internal_reason_phrase(), 
      _this->GetArenaForAllocation());
  }
  _impl_.last_modified_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.last_modified_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_last_modified().empty()) {
    _this->_impl_.last_modified_.Set(from._internal_last_modified(), 
      _this->GetArenaForAllocation());
  }
  _impl_.etag_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.etag_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_etag().empty()) {
    _this->_impl_.etag_.Set(from._internal_etag(), 
      _this->GetArenaForAllocation());
  }
  _impl_.body_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.body_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_body().empty()) {
    _this->_impl_.body_.Set(from._internal_body(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.stored_at_unix_sec_, &from._impl_.stored_at_unix_sec_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.status_code_) -
    reinterpret_cast<char*>(&_impl_.stored_at_unix_sec_)) + sizeof(_impl_.status_code_));
  // @@protoc_insertion_point(copy_constructor:hpserver.cache.HttpCacheEntry)
}

inline void HttpCacheEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.headers_){arena}
    , decltype(_impl_.vary_headers_){arena}
    , decltype(_impl_.reason_phrase_){}
    , decltype(_impl_.last_modified_){}
    , decltype(_impl_.etag_){}
    , decltype(_impl_.body_){}
    , decltype(_impl_.stored_at_unix_sec_){int64_t{0}}
    , decltype(_impl_.ttl_sec_){int64_t{0}}
    , decltype(_impl_.status_code_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.reason_phrase_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_phrase_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.last_modified_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.last_modified_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.etag_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.etag_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.body_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.body_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

HttpCacheEntry::~HttpCacheEntry() {
  // @@protoc_insertion_point(destructor:hpserver.cache.HttpCacheEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HttpCacheEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.headers_.~RepeatedPtrField();
  _impl_.vary_headers_.~RepeatedPtrField();
  _impl_.reason_phrase_.Destroy();
  _impl_.last_modified_.Destroy();
  _impl_.etag_.Destroy();
  _impl_.body_.Destroy();
}

void HttpCacheEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HttpCacheEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:hpserver.cache.HttpCacheEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.headers_.Clear();
  _impl_.vary_headers_.Clear();
  _impl_.reason_phrase_.ClearToEmpty();
  _impl_.last_modified_.ClearToEmpty();
  _impl_.etag_.ClearToEmpty();
  _impl_.body_.ClearToEmpty();
  ::memset(&_impl_.stored_at_unix_sec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.status_code_) -
      reinterpret_cast<char*>(&_impl_.stored_at_unix_sec_)) + sizeof(_impl_.status_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HttpCacheEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 status_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.status_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string reason_phrase = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_reason_phrase();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hpserver.cache.HttpCacheEntry.reason_phrase"));
        } else
          goto handle_unusual;
        continue;
      // string last_modified = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_last_modified();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hpserver.cache.HttpCacheEntry.last_modified"));
        } else
          goto handle_unusual;
        continue;
      // string etag = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_etag();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hpserver.cache.HttpCacheEntry.etag"));
        } else
          goto handle_unusual;
        continue;
      // int64 stored_at_unix_sec = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.stored_at_unix_sec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 ttl_sec = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.ttl_sec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .hpserver.cache.HeaderEntry headers = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_headers(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      // bytes body = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_body();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string vary_headers = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_vary_headers();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "hpserver.cache.HttpCacheEntry.vary_headers"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HttpCacheEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hpserver.cache.HttpCacheEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 status_code = 1;
  if (this->_internal_status_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_status_code(), target);
  }

  // string reason_phrase = 2;
  if (!this->_internal_reason_phrase().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason_phrase().data(), static_cast<int>(this->_internal_reason_phrase().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hpserver.cache.HttpCacheEntry.reason_phrase");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_reason_phrase(), target);
  }

  // string last_modified = 3;
  if (!this->_internal_last_modified().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_last_modified().data(), static_cast<int>(this->_internal_last_modified().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hpserver.cache.HttpCacheEntry.last_modified");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_last_modified(), target);
  }

  // string etag = 4;
  if (!this->_internal_etag().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_etag().data(), static_cast<int>(this->_internal_etag().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hpserver.cache.HttpCacheEntry.etag");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_etag(), target);
  }

  // int64 stored_at_unix_sec = 5;
  if (this->_internal_stored_at_unix_sec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_stored_at_unix_sec(), target);
  }

  // int64 ttl_sec = 6;
  if (this->_internal_ttl_sec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_ttl_sec(), target);
  }

  // repeated .hpserver.cache.HeaderEntry headers = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_headers_size()); i < n; i++) {
    const auto& repfield = this->_internal_headers(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  // bytes body = 8;
  if (!this->_internal_body().empty()) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_body(), target);
  }

  // repeated string vary_headers = 9;
  for (int i = 0, n = this->_internal_vary_headers_size(); i < n; i++) {
    const auto& s = this->_internal_vary_headers(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hpserver.cache.HttpCacheEntry.vary_headers");
    target = stream->WriteString(9, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hpserver.cache.HttpCacheEntry)
  return target;
}

size_t HttpCacheEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hpserver.cache.HttpCacheEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .hpserver.cache.HeaderEntry headers = 7;
  total_size += 1UL * this->_internal_headers_size();
  for (const auto& msg : this->_impl_.headers_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated string vary_headers = 9;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.vary_headers_.size());
  for (int i = 0, n = _impl_.vary_headers_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.vary_headers_.Get(i));
  }

  // string reason_phrase = 2;
  if (!this->_internal_reason_phrase().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason_phrase());
  }

  // string last_modified = 3;
  if (!this->_internal_last_modified().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_last_modified());
  }

  // string etag = 4;
  if (!this->_internal_etag().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_etag());
  }

  // bytes body = 8;
  if (!this->_internal_body().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_body());
  }

  // int64 stored_at_unix_sec = 5;
  if (this->_internal_stored_at_unix_sec() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_stored_at_unix_sec());
  }

  // int64 ttl_sec = 6;
  if (this->_internal_ttl_sec() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_ttl_sec());
  }

  // uint32 status_code = 1;
  if (this->_internal_status_code() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_status_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HttpCacheEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HttpCacheEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HttpCacheEntry::GetClassData() const { return &_class_data_; }


void HttpCacheEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HttpCacheEntry*>(&to_msg);
  auto& from = static_cast<const HttpCacheEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hpserver.cache.HttpCacheEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.headers_.MergeFrom(from._impl_.headers_);
  _this->_impl_.vary_headers_.MergeFrom(from._impl_.vary_headers_);
  if (!from._internal_reason_phrase().empty()) {
    _this->_internal_set_reason_phrase(from._internal_reason_phrase());
  }
  if (!from._internal_last_modified().empty()) {
    _this->_internal_set_last_modified(from._internal_last_modified());
  }
  if (!from._internal_etag().empty()) {
    _this->_internal_set_etag(from._internal_etag());
  }
  if (!from._internal_body().empty()) {
    _this->_internal_set_body(from._internal_body());
  }
  if (from._internal_stored_at_unix_sec() != 0) {
    _this->_internal_set_stored_at_unix_sec(from._internal_stored_at_unix_sec());
  }
  if (from._internal_ttl_sec() != 0) {
    _this->_internal_set_ttl_sec(from._internal_ttl_sec());
  }
  if (from._internal_status_code() != 0) {
    _this->_internal_set_status_code(from._internal_status_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HttpCacheEntry::CopyFrom(const HttpCacheEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hpserver.cache.HttpCacheEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HttpCacheEntry::IsInitialized() const {
  return true;
}

void HttpCacheEntry::InternalSwap(HttpCacheEntry* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.headers_.InternalSwap(&other->_impl_.headers_);
  _impl_.vary_headers_.InternalSwap(&other->_impl_.vary_headers_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.reason_phrase_, lhs_arena,
      &other->_impl_.reason_phrase_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.last_modified_, lhs_arena,
      &other->_impl_.last_modified_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.etag_, lhs_arena,
      &other->_impl_.etag_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.body_, lhs_arena,
      &other->_impl_.body_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HttpCacheEntry, _impl_.status_code_)
      + sizeof(HttpCacheEntry::_impl_.status_code_)
      - PROTOBUF_FIELD_OFFSET(HttpCacheEntry, _impl_.stored_at_unix_sec_)>(
          reinterpret_cast<char*>(&_impl_.stored_at_unix_sec_),
          reinterpret_cast<char*>(&other->_impl_.stored_at_unix_sec_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HttpCacheEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_http_5fcache_2eproto_getter, &descriptor_table_http_5fcache_2eproto_once,
      file_level_metadata_http_5fcache_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace cache
}  // namespace hpserver
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hpserver::cache::HeaderEntry*
Arena::CreateMaybeMessage< ::hpserver::cache::HeaderEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hpserver::cache::HeaderEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::hpserver::cache::HttpCacheEntry*
Arena::CreateMaybeMessage< ::hpserver::cache::HttpCacheEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hpserver::cache::HttpCacheEntry >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
